spring.datasource.url=jdbc:postgresql://172.31.252.129:5432/Paas-TP1

spring.datasource.username=admin
spring.datasource.password=paaspassword

spring.jpa.hibernate.ddl-auto=none

spring.redis.cluster.nodes=172.31.250.176:7000,172.31.250.176:7001,172.31.250.176:7002,172.31.253.41:7000,172.31.253.41:7001,172.31.253.41:7002
spring.redis.port=7000

spring.cache.type=redis
spring.cache.redis.time-to-live=600000

server.port=8083

spring.config.activate.on-profile=cache-loader
