upstream Entrance_cockpit_backend{
    server 172.31.253.122:8086;
    server 172.31.253.113:8086;
    # rajouter des ip ici pour lb
}

    # Mapping IP backend -> label
    map $upstream_addr $backend_label {
        ~^172\.31\.253\.122:8086 core_backend1;
        ~^172\.31\.253\.113:8086 core_backend2;
        default unknown;
    }

    log_format cockpit_log
        '$remote_addr [$time_local] '
        'backend=$backend_label '
        'addr=$upstream_addr ';

server {
    listen 8086;
    access_log /var/log/nginx/cockpit_backend.log cockpit_log;
    proxy_pass Entrance_cockpit_backend;

}