version: "3.9"

services:

  redis-1:
    image: redis:7
    container_name: redis-1
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:6379"

  redis-2:
    image: redis:7
    container_name: redis-2
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:6379"

  redis-3:
    image: redis:7
    container_name: redis-3
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7003:6379"

  redis-4:
    image: redis:7
    container_name: redis-4
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7004:6379"

  redis-5:
    image: redis:7
    container_name: redis-5
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7005:6379"

  redis-6:
    image: redis:7
    container_name: redis-6
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7006:6379"

  spring-app:
    build:
      context: .
    container_name: spring-app
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: cache-loader
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.31.252.129:5432/Paas-TP1
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: paaspassword
      SPRING_REDIS_CLUSTER_NODES: redis-1:6379,redis-2:6379,redis-3:6379
    ports:
      - "8083:8083"
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
